package com.sunian.dao.mapper.test2;

import com.sunian.dao.model.test2.TfsDept;
import com.sunian.dao.model.test2.TfsDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TfsDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    long countByExample(TfsDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int deleteByExample(TfsDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int insert(TfsDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int insertSelective(TfsDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    List<TfsDept> selectByExample(TfsDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    TfsDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") TfsDept record, @Param("example") TfsDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int updateByExample(@Param("record") TfsDept record, @Param("example") TfsDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(TfsDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tf_s_dept
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    int updateByPrimaryKey(TfsDept record);
}