package com.sunian.dao.model.test2;

public class TfsDept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_s_dept.id
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tf_s_dept.dept_name
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_s_dept.id
     *
     * @return the value of tf_s_dept.id
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_s_dept.id
     *
     * @param id the value for tf_s_dept.id
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tf_s_dept.dept_name
     *
     * @return the value of tf_s_dept.dept_name
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tf_s_dept.dept_name
     *
     * @param deptName the value for tf_s_dept.dept_name
     *
     * @mbg.generated Tue Jul 23 16:25:36 GMT+08:00 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}