server:
  port: 18000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
      routes:
      - id: blog-service
        # uri就是目标服务地址,这里使用服务名的方式，gateway会帮我们去注册中心中获取服务列表
        uri: lb://blog-service
        predicates:
        - Path=/blog/**
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path=/user/**
      - id: security-service
        uri: lb://security-service
        predicates:
        - Path=/hello/**

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    # 当前服务实例规则，在界面展示样式：192.168.1.46:user-service:18000
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/