
server:
  port: 18001
spring:
  application:
    name: blog-service
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    # 当前服务实例规则，在界面展示样式：192.168.1.46:user-service:18000
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  #设置openFeign的超时时间，如果只是开启hystrix，则超时时间不生效，还是默认1000；如果要生效，还需要设置hystrix超时时间，大于openFeign的超时时间，不然也不生效
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        oggerLevel: basic
  #开启hystrix服务熔断，降级配置，如果没开启则报500错误，开启则返回hystrix服务熔断定制错误
  hystrix:
    enabled: true

#设置hystrix超时时间，最终以openFeign超时时间为准
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
