
server:
  port: 18003
spring:
  application:
    name: security-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://47.102.46.30:3306/springboot_test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC

eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则 ，当前服务实例规则，在界面展示样式：192.168.1.46:user-service:18000
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

mybatis:
  mapper-locations: classpath*:/sql/mapper/*.xml